#!/usr/bin/env python
# -*- coding:utf-8 -*-

"""
Copyright 2011 Ryan Flynn <parseerror@gmail.com>
"""

# Ref: http://meiert.com/en/indices/css-properties/
# Ref: http://www.blooberry.com/indexdot/css/propindex/all.htm
PROPERTIES = {
	'accelerator'			: ('IE5',),
	'alignment-adjust'		: ('CSS3',),
	'animation'			: ('CSS3',),
	'animation-delay'		: ('CSS3',),
	'animation-direction'		: ('CSS3',),
	'animation-duration'		: ('CSS3',),
	'animation-iteration-count'	: ('CSS3',),
	'animation-name'		: ('CSS3',),
	'animation-play-state'		: ('CSS3',),
	'animation-timing-function'	: ('CSS3',),
	'appearance'			: ('CSS3',),
	'azimuth'			: ('CSS2',),
	'backface-visibility'		: ('CSS3',),
	'background'			: ('CSS1',),
	'background-attachment'		: ('CSS1',),
	'background-break'		: ('CSS3',),
	'background-clip'		: ('CSS3',),
	'background-color'		: ('CSS1',),
	'background-image'		: ('CSS1',),
	'background-origin'		: ('CSS3',),
	'background-position'		: ('CSS1',),
	'background-position-x'		: ('CSS1',),
	'background-position-y'		: ('CSS1',),
	'background-repeat'		: ('CSS1',),
	'background-size'		: ('CSS3',),
	'baseline-shift'		: ('CSS3',),
	'binding'			: ('CSS3',),
	'bleed'				: ('CSS3',),
	'behavior'			: ('IE5',),
	'bookmark-label'		: ('CSS3',),
	'bookmark-level'		: ('CSS3',),
	'bookmark-state'		: ('CSS3',),
	'bookmark-target'		: ('CSS3',),
	'border'			: ('CSS1',),
	'border-bottom'			: ('CSS1',),
	'border-bottom-color'		: ('CSS2',),
	'border-bottom-left-radius'	: ('CSS3',),
	'border-bottom-right-radius'	: ('CSS3',),
	'border-bottom-style'		: ('CSS2',),
	'border-bottom-width'		: ('CSS1',),
	'border-collapse'		: ('CSS2',),
	'border-color'			: ('CSS1',),
	'border-image'			: ('CSS3',),
	'border-image-outset'		: ('CSS3',),
	'border-image-repeat'		: ('CSS3',),
	'border-image-slice'		: ('CSS3',),
	'border-image-source'		: ('CSS3',),
	'border-image-width'		: ('CSS3',),
	'border-left'			: ('CSS1',),
	'border-left-color'		: ('CSS2',),
	'border-left-style'		: ('CSS2',),
	'border-left-width'		: ('CSS1',),
	'border-radius'			: ('CSS3',),
	'border-right'			: ('CSS1',),
	'border-right-color'		: ('CSS2',),
	'border-right-style'		: ('CSS2',),
	'border-right-width'		: ('CSS1',),
	'border-spacing'		: ('CSS2',),
	'border-style'			: ('CSS1',),
	'border-top'			: ('CSS1',),
	'border-top-color'		: ('CSS2',),
	'border-top-left-radius'	: ('CSS3',),
	'border-top-right-radius'	: ('CSS3',),
	'border-top-style'		: ('CSS2',),
	'border-top-width'		: ('CSS1',),
	'border-width'			: ('CSS1',),
	'bottom'			: ('CSS2',),
	'box-align'			: ('CSS3',),
	'box-decoration-break'		: ('CSS3',),
	'box-direction'			: ('CSS3',),
	'box-flex'			: ('CSS3',),
	'box-flex-group'		: ('CSS3',),
	'box-lines'			: ('CSS3',),
	'box-ordinal-group'		: ('CSS3',),
	'box-orient'			: ('CSS3',),
	'box-pack'			: ('CSS3',),
	'box-shadow'			: ('CSS3',),
	'box-sizing'			: ('CSS3',),
	'break-after'			: ('CSS3',),
	'break-before'			: ('CSS3',),
	'break-inside'			: ('CSS3',),
	'caption-side'			: ('CSS2',),
	'clear'				: ('CSS1',),
	'clip'				: ('CSS2',),
	'color'				: ('CSS1',),
	'color-profile'			: ('CSS3',),
	'column-count'			: ('CSS3',),
	'column-fill'			: ('CSS3',),
	'column-gap'			: ('CSS3',),
	'column-rule'			: ('CSS3',),
	'column-rule-color'		: ('CSS3',),
	'column-rule-style'		: ('CSS3',),
	'column-rule-width'		: ('CSS3',),
	'column-span'			: ('CSS3',),
	'column-width'			: ('CSS3',),
	'columns'			: ('CSS3',),
	'content'			: ('CSS2',),
	'counter-increment'		: ('CSS2',),
	'counter-reset'			: ('CSS2',),
	'crop'				: ('CSS3',),
	'cue'				: ('CSS2',),
	'cue-after'			: ('CSS2',),
	'cue-before'			: ('CSS2',),
	'cursor'			: ('CSS2',),
	'direction'			: ('CSS2',),
	'display'			: ('CSS1',),
	'dominant-baseline'		: ('CSS3',),
	'drop-initial-after-adjust'	: ('CSS3',),
	'drop-initial-after-align'	: ('CSS3',),
	'drop-initial-before-adjust'	: ('CSS3',),
	'drop-initial-before-align'	: ('CSS3',),
	'drop-initial-size'		: ('CSS3',),
	'drop-initial-value'		: ('CSS3',),
	'elevation'			: ('CSS2',),
	'empty-cells'			: ('CSS2',),
	'fit'				: ('CSS3',),
	'fit-position'			: ('CSS3',),
	'filter'			: ('IE',),
	'float'				: ('CSS1',),
	'float-offset'			: ('CSS3',),
	'font'				: ('CSS1',),
	'font-family'			: ('CSS1',),
	'font-size'			: ('CSS1',),
	'font-size-adjust'		: ('CSS2',),
	'font-stretch'			: ('CSS3',),
	'font-style'			: ('CSS1',),
	'font-variant'			: ('CSS1',),
	'font-weight'			: ('CSS1',),
	'grid-columns'			: ('CSS3',),
	'grid-rows'			: ('CSS3',),
	'hanging-punctuation'		: ('CSS3',),
	'height'			: ('CSS1',),
	'_height'			: ('IE-hack',),
	'hyphenate-after'		: ('CSS3',),
	'hyphenate-before'		: ('CSS3',),
	'hyphenate-character'		: ('CSS3',),
	'hyphenate-lines'		: ('CSS3',),
	'hyphenate-resource'		: ('CSS3',),
	'hyphens'			: ('CSS3',),
	'icon'				: ('CSS3',),
	'image-orientation'		: ('CSS3',),
	'image-rendering'		: ('CSS3',),
	'image-resolution'		: ('CSS3',),
	'inline-box-align'		: ('CSS3',),
	'ime-mode'			: ('IE5',),
	'include-source'		: ('Netscape4.x',),
	'layer-background-color'	: ('Netscape4.x',),
	'layer-background-image'	: ('Netscape4.x',),
	'layout-flow'			: ('IE5',),
	'layout-grid'			: ('IE5',),
	'layout-grid-char'		: ('IE5',),
	'layout-grid-char-spacing'	: ('IE5',),
	'layout-grid-line'		: ('IE5',),
	'layout-grid-mode'		: ('IE5',),
	'layout-grid-type'		: ('IE5',),
	'left'				: ('CSS2',),
	'letter-spacing'		: ('CSS1',),
	'line-break'			: ('IE5',),
	'line-height'			: ('CSS1',),
	'line-stacking'			: ('CSS3',),
	'line-stacking-ruby'		: ('CSS3',),
	'line-stacking-shift'		: ('CSS3',),
	'line-stacking-strategy'	: ('CSS3',),
	'list-style'			: ('CSS1',),
	'list-style-image'		: ('CSS1',),
	'list-style-position'		: ('CSS1',),
	'list-style-type'		: ('CSS1',),
	'margin'			: ('CSS1',),
	'margin-bottom'			: ('CSS1',),
	'margin-left'			: ('CSS1',),
	'margin-right'			: ('CSS1',),
	'margin-top'			: ('CSS1',),
	'mark'				: ('CSS3',),
	'mark-after'			: ('CSS3',),
	'mark-before'			: ('CSS3',),
	'marker-offset'			: ('CSS2',),
	'marks'				: ('CSS2',),
	'marquee-direction'		: ('CSS3',),
	'marquee-play-count'		: ('CSS3',),
	'marquee-speed'			: ('CSS3',),
	'marquee-style'			: ('CSS3',),
	'max-height'			: ('CSS2',),
	'max-width'			: ('CSS2',),
	'min-height'			: ('CSS2',),
	'min-width'			: ('CSS2',),
	'move-to'			: ('CSS3',),
	'nav-down'			: ('CSS3',),
	'nav-index'			: ('CSS3',),
	'nav-left'			: ('CSS3',),
	'nav-up'			: ('CSS3',),
	'opacity'			: ('CSS3',),
	'orphans'			: ('CSS2',),
	'outline'			: ('CSS2',),
	'outline-color'			: ('CSS2',),
	'outline-offset'		: ('CSS3',),
	'outline-style'			: ('CSS2',),
	'outline-width'			: ('CSS2',),
	'overflow'			: ('CSS2',),
	'overflow-X'			: ('CSS3',),
	'overflow-Y'			: ('CSS3',),
	'padding'			: ('CSS1',),
	'padding-bottom'		: ('CSS1',),
	'padding-left'			: ('CSS1',),
	'padding-right'			: ('CSS1',),
	'padding-top'			: ('CSS1',),
	'page'				: ('CSS2',),
	'page-break-after'		: ('CSS2',),
	'page-break-before'		: ('CSS2',),
	'page-break-inside'		: ('CSS2',),
	'pause'				: ('CSS2',),
	'pause-after'			: ('CSS2',),
	'pause-before'			: ('CSS2',),
	'perspective'			: ('CSS3',),
	'perspective-origin'		: ('CSS3',),
	'phonemes'			: ('CSS3',),
	'pitch'				: ('CSS2',),
	'pitch-range'			: ('CSS2',),
	'play-during'			: ('CSS2',),
	'position'			: ('CSS2',),
	'presentation-level'		: ('CSS3',),
	'presentation-trim'		: ('CSS3',),
	'quotes'			: ('CSS2',),
	'richness'			: ('CSS2',),
	'right'				: ('CSS2',),
	'ruby-align'			: ('CSS3',),
	'ruby-overhang'			: ('CSS3',),
	'ruby-position'			: ('CSS3',),
	'ruby-span'			: ('CSS3',),
	'size'				: ('CSS2',),
	'speak'				: ('CSS2',),
	'speak-header'			: ('CSS2',),
	'speak-numeral'			: ('CSS2',),
	'speak-punctuation'		: ('CSS2',),
	'speech-rate'			: ('CSS2',),
	'stress'			: ('CSS2',),
	'string-set'			: ('CSS3',),
	'scrollbar-arrow-color'		: ('IE5.5/Opera7',),
	'scrollbar-base-color'		: ('IE5.5/Opera7',),
	'scrollbar-dark-shadow-color'	: ('IE5.5/Opera7',),
	'scrollbar-face-color'		: ('IE5.5/Opera7',),
	'scrollbar-highlight-color'	: ('IE5.5/Opera7',),
	'scrollbar-shadow-color'	: ('IE5.5/Opera7',),
	'scrollbar-3d-light-color'	: ('IE5.5/Opera7',),
	'scrollbar-track-color'		: ('IE5.5/Opera7',),
	'table-layout'			: ('CSS2',),
	'target'			: ('CSS3',),
	'target-name'			: ('CSS3',),
	'target-new'			: ('CSS3',),
	'target-position'		: ('CSS3',),
	'text-align'			: ('CSS1',),
	'text-align-last'		: ('CSS3',),
	'text-autospace'		: ('IE5',),
	'text-decoration'		: ('CSS1',),
	'text-emphasis'			: ('CSS3',),
	'text-height'			: ('CSS3',),
	'text-indent'			: ('CSS1',),
	'text-justify'			: ('CSS3',),
	'text-kashida-space'		: ('IE5.5',),
	'text-outline'			: ('CSS3',),
	'text-overflow'			: ('IE6',),
	'text-shadow'			: ('CSS2',),
	'text-transform'		: ('CSS1',),
	'text-underline-position'	: ('IE6',),
	'text-wrap'			: ('CSS3',),
	'top'				: ('CSS2',),
	'transform'			: ('CSS3',),
	'transform-origin'		: ('CSS3',),
	'transform-style'		: ('CSS3',),
	'transition'			: ('CSS3',),
	'transition-delay'		: ('CSS3',),
	'transition-duration'		: ('CSS3',),
	'transition-property'		: ('CSS3',),
	'transition-timing-function'	: ('CSS3',),
	'unicode-bidi'			: ('CSS2',),
	'vertical-align'		: ('CSS1',),
	'visibility'			: ('CSS2',),
	'voice-balance'			: ('CSS3',),
	'voice-duration'		: ('CSS3',),
	'voice-family'			: ('CSS2',),
	'voice-pitch'			: ('CSS3',),
	'voice-rate'			: ('CSS3',),
	'voice-stress'			: ('CSS3',),
	'voice-volume'			: ('CSS3',),
	'volume'			: ('CSS2',),
	'white-space'			: ('CSS1',),
	'white-space-collapse'		: ('CSS3',),
	'widows'			: ('CSS2',),
	'width'				: ('CSS1',),
	'word-break'			: ('CSS3',),
	'word-spacing'			: ('CSS1',),
	'word-wrap'			: ('CSS3',),
	'writing-mode'			: ('IE5.5',),
	'z-index'			: ('CSS2',),
	'zoom'				: ('IE5.5',),
}

def check_properties(doc):
	for r in doc.rules:
		decls = r.decls.decl
		for d in decls:
			p = d.property.lower()
			if p not in PROPERTIES:
				if not p.startswith('-'): # non-standard extensions
					print 'Unknown property: "%s": %s: %s' % (
						d.property, d.property, ''.join(v.format() for v in d.values))

def readfile(args):
	"""convenience function to read from stdin, filename or URL"""
	contents = None
	if args:
		filename = args[0]
		if filename.startswith('http://') \
		   or filename.startswith('https://') \
		   or filename.startswith('ftp://'):
			resp = urllib2.urlopen(filename)
			contents = resp.read()
		else:
			f = open(filename, 'r')
			contents = f.read()
			f.close()
	else:
		filename = '-'
		contents = sys.stdin.read()
	return (filename, contents)

if __name__ == '__main__':

	import urllib2
	import sys
	from optparse import OptionParser

	import parse as cssparse

	op = OptionParser()
	#op.add_option('--standards', action='store_true', help='print a nicely formatted, indented representation')
	(Opts, Args) = op.parse_args()

	filename, contents = get_contents(Args)

	doc = cssparse.CSSDoc.parse(contents)

	check_properties(doc)

	# TODO:
	# check for non-web-standard fonts
	# check for non-standard color names

